Repository HUFSummer-Hackathon/NomadWorker-Android, pull requests merged in 2022-09, with the labels that each got.

#88 Feat/86 place scrap
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/place/PlaceDetailRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/settings/SettingsRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/place/PlaceDetailDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/settings/SettingsRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/PlaceMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/SettingsMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/place/PlaceScrapRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/place/PlaceScrapResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/settings/PlaceScrapListResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/place/PlaceDetailRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/settings/SettingsRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/place/PlaceScrapResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/settings/PlaceScrapListResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/place/PlaceDetailRepository.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/settings/SettingsRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/PlaceScrapAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsPlaceScrapFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsViewModel.kt
  app/src/main/res/layout/item_place_scrap.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/colors.xml
Labels: 재성, feature

#91 Feat/90 qa sign up
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpEmailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpPasswordFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpVerifyFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpViewModel.kt
  app/src/main/res/layout/fragment_sign_up_verify.xml
  app/src/main/res/values/strings.xml
Labels: 승민, refactor, layout, DONE

#92 Add/89 app resources
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
Labels: 재성, resource, DONE, QA

#95 Feat/93 scrap
  app/src/main/java/com/comjeong/nomadworker/data/mapper/PlaceMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/place/PlaceDetailResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/place/PlaceScrapRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/place/PlaceDetailResult.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceDetailViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/PlaceScrapAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsPlaceScrapFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsViewModel.kt
  app/src/main/res/drawable/ic_scrap_disable_28.xml
  app/src/main/res/drawable/selector_scrap.xml
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/layout/item_place_scrap.xml
  app/src/main/res/menu/menu_bookmark.xml
  app/src/main/res/values/colors.xml
Labels: 재성, feature, IN PROGRESS

#97 Feat/94 qa sign up
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpEmailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpNickNameFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpPasswordFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpVerifyFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpViewModel.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/fragment_sign_up_email.xml
  app/src/main/res/layout/fragment_sign_up_nick_name.xml
  app/src/main/res/layout/fragment_sign_up_password.xml
  app/src/main/res/values/strings.xml
Labels: 승민, fix, layout, DONE, QA

#99 Feat/98 qa new feed
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedContentChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedPhotoChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedPlaceChoiceFragment.kt
  app/src/main/res/layout/fragment_new_feed_content_choice.xml
  app/src/main/res/values/strings.xml
Labels: 승민, refactor, layout, DONE, QA

#101 [QA] #100 스크롤 뷰 내 구글맵의 스크롤기능이 잘 작동하도록 코드 추가
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceDetailFragment.kt
  app/src/main/res/layout/fragment_place_detail.xml
Labels: 승민, fix, DONE, QA

#102 Fix/96 feed detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/data/mapper/MyPageMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/mypage/UserFeedDetailResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/mypage/UserFeedDetailResult.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BindingAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/newfeed/NewFeedActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/newfeed/NewFeedAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/newfeed/NewFeedContentChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/newfeed/NewFeedInfo.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/newfeed/NewFeedPhotoChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/newfeed/NewFeedPlaceChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageUserFeedDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyViewModel.kt
  app/src/main/res/drawable/ic_like_20.xml
  app/src/main/res/drawable/ic_like_activate_24.xml
  app/src/main/res/drawable/ic_like_disable_24.xml
  app/src/main/res/drawable/selector_like_heart.xml
  app/src/main/res/layout/activity_new_feed.xml
  app/src/main/res/layout/dialog_reply_option.xml
  app/src/main/res/layout/fragment_my_page_user_feed_detail.xml
  app/src/main/res/layout/fragment_new_feed_content_choice.xml
  app/src/main/res/layout/fragment_new_feed_photo_choice.xml
  app/src/main/res/layout/fragment_new_feed_place_choice.xml
  app/src/main/res/layout/item_feed_main.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/navigation/nav_new_feed.xml
Labels: 재성, DONE, QA
