Repository HUFSummer-Hackathon/NomadWorker-Android, pull requests merged in 2022-08, with the labels that each got.

#52 [FIX] #50 닉네임 중복 확인 에러 수정
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
Labels: 재성, fix, DONE

#53 [FIX] #51 로그아웃 구현
  app/src/main/java/com/comjeong/nomadworker/data/datasource/local/NomadSharedPreferences.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageSettingBottomSheetFragment.kt
  app/src/main/res/values/styles.xml
Labels: 재성, feature, DONE

#55 Feat/36 new feed
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/feed/FeedsRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/feed/FeedsDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/FeedMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/feed/NewFeedPlaceSearchResultResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/feed/PostNewFeedResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/NetworkInterceptor.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/FeedApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/feed/FeedRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/feed/PostNewFeedResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/place/NewFeedPlaceSearchResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/feed/FeedRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/DialogUtil.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedContentChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedInfo.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedPhotoChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedPlaceChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/permission/UserPermission.kt
  app/src/main/java/com/comjeong/nomadworker/ui/search/SearchOptionFragment.kt
  app/src/main/res/layout/fragment_new_feed_content_choice.xml
  app/src/main/res/layout/fragment_new_feed_photo_choice.xml
  app/src/main/res/layout/fragment_new_feed_place_choice.xml
  app/src/main/res/layout/item_new_feed_place_search.xml
Labels: 승민, feature, DONE

#56 Feat/54 user profile
  app/src/main/java/com/comjeong/nomadworker/NomadWorkerApplication.kt
  app/src/main/java/com/comjeong/nomadworker/common/BitmapRequestBody.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/local/NomadSharedPreferences.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/mypage/MyPageRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/mypage/MyPageDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/MyPageMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/SignInMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/SignUpMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/mypage/ProfileImageResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/mypage/UserTotalFeedsResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/mypage/UserTotalFeedsWithInfoResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/signin/SignInResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/signup/SignUpResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/FeedApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/mypage/MyPageRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/feed/UserTotalFeedsWithInfoResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/mypage/ProfileImageResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/mypage/UserInfoResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/signin/SignInResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/signup/SignUpResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/mypage/MyPageRepository.kt
  app/src/main/java/com/comjeong/nomadworker/model/UserInfo.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageUserFeedDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/UserFeedAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signin/SignInViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage_user_feed.xml
Labels: 재성, feature, DONE

#59 Feat/57 place search
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/search/PlaceSearchDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/search/PlaceSearchDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/SearchMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/search/PlaceSearchResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/PlaceApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/search/PlaceSearchRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/search/PlaceSearchResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/search/PlaceSearchRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/search/SearchAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/search/SearchFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/search/SearchOptionFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/selector_chip_background.xml
  app/src/main/res/drawable/selector_chip_stroke.xml
  app/src/main/res/drawable/selector_chip_text_color.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_option.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/menu/menu_bottom.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 승민, feature, DONE

#60 Feat/58 feed like
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/feed/FeedsRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/feed/FeedsDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/FeedMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/feed/FeedLikeRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/feed/FeedLikeResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/feed/TotalFeedsResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/FeedApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/feed/FeedRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/feed/FeedLikeResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/feed/TotalFeedsResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/feed/FeedRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BindingAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/extension/EditTextExt.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/extension/LiveDataExt.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpNickNameFragment.kt
  app/src/main/res/drawable/selector_like_heart.xml
  app/src/main/res/layout/item_feed_main.xml
Labels: 재성, feature, DONE

#63 [UI] #61 댓글 UI 구현
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyAuthorTopAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyOthersAdapter.kt
  app/src/main/res/layout/fragment_feed_reply.xml
  app/src/main/res/layout/item_feed_reply_author.xml
  app/src/main/res/layout/item_feed_reply_others.xml
  app/src/main/res/values/styles.xml
Labels: 재성, layout, DONE

#65 Feat/62 place detail layout
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceDetailFragment.kt
  app/src/main/res/drawable/bg_white_radius_10.xml
  app/src/main/res/drawable/ic_bookmark_28.xml
  app/src/main/res/drawable/ic_place_detail_address_22.xml
  app/src/main/res/drawable/ic_place_detail_charge_24.xml
  app/src/main/res/drawable/ic_place_detail_clock_16.xml
  app/src/main/res/drawable/ic_place_detail_info_20.xml
  app/src/main/res/drawable/ic_place_detail_location_24.xml
  app/src/main/res/drawable/ic_place_detail_wifi_24.xml
  app/src/main/res/layout/dialog_evaluation.xml
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/layout/item_home_nearby.xml
  app/src/main/res/layout/item_home_recommend.xml
  app/src/main/res/menu/menu_bookmark.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 승민, layout, DONE

#66 Layout/64 settings
  app/build.gradle
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/local/SettingsLocalDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/mypage/MyPageRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/settings/SettingsRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/mypage/MyPageDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/settings/SettingsLocalDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/settings/SettingsRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/settings/NoticeLocalData.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/mypage/MyPageRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/settings/SettingsRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/mypage/MyPageRepository.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/settings/SettingsRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BindingAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/CustomDialog.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/NoticeAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsContactFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsNoticeFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsPrivacyFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsProfileFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsReportFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsTosFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsViewModel.kt
  app/src/main/res/drawable/ic_arrow_down_24.xml
  app/src/main/res/drawable/ic_notice_accent.xml
  app/src/main/res/layout/dialog_basic_custom.xml
  app/src/main/res/layout/fragment_my_page_setting_bottom_sheet.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_settings_contact.xml
  app/src/main/res/layout/fragment_settings_notice.xml
  app/src/main/res/layout/fragment_settings_privacy.xml
  app/src/main/res/layout/fragment_settings_profile.xml
  app/src/main/res/layout/fragment_settings_report.xml
  app/src/main/res/layout/fragment_settings_tos.xml
  app/src/main/res/layout/item_settings_notice.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: 재성, feature, layout, DONE

#68 [FIX] #67 검색 탭 네비게이션 바 오류 수정
  app/src/main/java/com/comjeong/nomadworker/ui/MainActivity.kt
Labels: 재성, fix, DONE

#71 [FEAT] #69 장소 스크랩 UI 구현
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsPlaceScrapFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsProfileFragment.kt
  app/src/main/res/drawable/ic_scrap_activate_28.xml
  app/src/main/res/drawable/ic_scrap_disable_28.xml
  app/src/main/res/drawable/ic_star_rate_16.xml
  app/src/main/res/drawable/ic_star_rate_28.xml
  app/src/main/res/drawable/img_empty_data.xml
  app/src/main/res/drawable/selector_scrap.xml
  app/src/main/res/layout/fragment_settings_place_scrap.xml
  app/src/main/res/layout/item_place_scrap.xml
  app/src/main/res/layout/view_place_scrap_empty.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/styles.xml
Labels: 재성, layout, DONE

#73 Feat/70 comment
  app/build.gradle
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/reply/ReplyDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/reply/ReplyDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/ReplyMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/reply/DeleteReplyRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/reply/DeleteReplyResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/reply/GetReplyResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/reply/PostReplyRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/reply/PostReplyResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/ReplyApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/reply/ReplyRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/NetworkModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/reply/Author.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/reply/DeleteReplyResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/reply/GetReplyResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/reply/PostReplyResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/reply/ReplyRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BindingAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageUserFeedDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceRegionViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyAuthorTopAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyOthersAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyViewModel.kt
  app/src/main/res/drawable/ic_option_14.xml
  app/src/main/res/drawable/ic_option_24.xml
  app/src/main/res/drawable/ic_reply_24.xml
  app/src/main/res/layout/dialog_reply_option.xml
  app/src/main/res/layout/fragment_feed_reply.xml
  app/src/main/res/layout/fragment_my_page_user_feed_detail.xml
  app/src/main/res/layout/item_feed_main.xml
  app/src/main/res/layout/item_feed_reply_author.xml
  app/src/main/res/layout/item_feed_reply_others.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
Labels: 승민, feature, DONE

#76 Feat/74 fix reply
  app/src/main/java/com/comjeong/nomadworker/data/mapper/ReplyMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/reply/GetReplyResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/reply/GetReplyResult.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageUserFeedDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/reply/ReplyViewModel.kt
Labels: 승민, fix, refactor, DONE

#79 [FIX] #75 장소 상세에서 지도가 표시되지 않는 오류를 수정
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceDetailFragment.kt
Labels: 승민, fix, layout, DONE

#83 Feat/81 place scrap
  app/build.gradle
  app/src/main/java/com/comjeong/nomadworker/common/UiState.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/settings/SettingsRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/settings/SettingsRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/SettingsMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/settings/PlaceScrapResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/settings/SettingsRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/settings/PlaceScrapResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/settings/SettingsRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/base/BaseActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/base/BaseFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/customview/CustomSpinner.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/PlaceScrapAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsPlaceScrapFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/setting/SettingsViewModel.kt
  app/src/main/res/layout/fragment_settings_place_scrap.xml
  app/src/main/res/layout/item_place_scrap.xml
  app/src/main/res/layout/spinner_loading.xml
  app/src/main/res/layout/view_place_scrap_empty.xml
  app/src/main/res/values/strings.xml
  build.gradle
  settings.gradle
Labels: 재성, feature, layout, DONE

#85 [UI] #82 온보딩 레이아웃 추가
  app/src/main/java/com/comjeong/nomadworker/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-hdpi/img_onboard_first.png
  app/src/main/res/drawable-hdpi/img_onboard_second.png
  app/src/main/res/drawable-hdpi/img_onboard_third.png
  app/src/main/res/drawable-xhdpi/img_onboard_first.png
  app/src/main/res/drawable-xhdpi/img_onboard_second.png
  app/src/main/res/drawable-xhdpi/img_onboard_third.png
  app/src/main/res/drawable-xxhdpi/img_onboard_first.png
  app/src/main/res/drawable-xxhdpi/img_onboard_second.png
  app/src/main/res/drawable-xxhdpi/img_onboard_third.png
  app/src/main/res/drawable-xxxhdpi/img_onboard_first.png
  app/src/main/res/drawable-xxxhdpi/img_onboard_second.png
  app/src/main/res/drawable-xxxhdpi/img_onboard_third.png
  app/src/main/res/layout/fragment_on_boarding_first.xml
  app/src/main/res/layout/fragment_on_boarding_second.xml
  app/src/main/res/layout/fragment_on_boarding_third.xml
  app/src/main/res/values/strings.xml
Labels: 승민, layout, DONE

#87 [FEAT] #84 피드 삭제 및 피드 등록 API 일부 수정
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/mypage/MyPageRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/mypage/MyPageDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/MyPageMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/mypage/DeleteFeedResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/FeedApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/mypage/MyPageRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/mypage/DeleteFeedResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/mypage/MyPageRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageUserFeedDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageViewModel.kt
  app/src/main/res/drawable/ic_option_black_24.xml
  app/src/main/res/layout/fragment_my_page_user_feed_detail.xml
  app/src/main/res/menu/menu_feed_detail_option.xml
  app/src/main/res/values/strings.xml
Labels: 승민, feature, refactor, DONE
