Repository HUFSummer-Hackathon/NomadWorker-Android, pull requests merged in 2022-07, with the labels that each got.

#2 [ADD] 필요 리소스 추가
  app/src/main/res/drawable-hdpi/img_busan.png
  app/src/main/res/drawable-hdpi/img_gangneung.png
  app/src/main/res/drawable-hdpi/img_home_banner.png
  app/src/main/res/drawable-hdpi/img_jeju.png
  app/src/main/res/drawable-hdpi/img_logo.png
  app/src/main/res/drawable-hdpi/img_seoul.png
  app/src/main/res/drawable-mdpi/img_busan.png
  app/src/main/res/drawable-mdpi/img_gangneung.png
  app/src/main/res/drawable-mdpi/img_home_banner.png
  app/src/main/res/drawable-mdpi/img_jeju.png
  app/src/main/res/drawable-mdpi/img_logo.png
  app/src/main/res/drawable-mdpi/img_seoul.png
  app/src/main/res/drawable-xhdpi/img_busan.png
  app/src/main/res/drawable-xhdpi/img_gangneung.png
  app/src/main/res/drawable-xhdpi/img_home_banner.png
  app/src/main/res/drawable-xhdpi/img_jeju.png
  app/src/main/res/drawable-xhdpi/img_logo.png
  app/src/main/res/drawable-xhdpi/img_seoul.png
  app/src/main/res/drawable-xxhdpi/img_busan.png
  app/src/main/res/drawable-xxhdpi/img_gangneung.png
  app/src/main/res/drawable-xxhdpi/img_home_banner.png
  app/src/main/res/drawable-xxhdpi/img_jeju.png
  app/src/main/res/drawable-xxhdpi/img_logo.png
  app/src/main/res/drawable-xxhdpi/img_seoul.png
  app/src/main/res/drawable-xxxhdpi/img_busan.png
  app/src/main/res/drawable-xxxhdpi/img_gangneung.png
  app/src/main/res/drawable-xxxhdpi/img_home_banner.png
  app/src/main/res/drawable-xxxhdpi/img_jeju.png
  app/src/main/res/drawable-xxxhdpi/img_logo.png
  app/src/main/res/drawable-xxxhdpi/img_seoul.png
  app/src/main/res/drawable/bg_blue_radius_10.xml
  app/src/main/res/drawable/bg_bluegrey_radius_10.xml
  app/src/main/res/drawable/bg_green_radius_10.xml
  app/src/main/res/drawable/bg_grey06_radius_10.xml
  app/src/main/res/drawable/bg_red_radius_10.xml
  app/src/main/res/drawable/bg_white_radius_10_stroke_blue.xml
  app/src/main/res/drawable/ic_add_24.xml
  app/src/main/res/drawable/ic_back_24.xml
  app/src/main/res/drawable/ic_camera_24.xml
  app/src/main/res/drawable/ic_close_24.xml
  app/src/main/res/drawable/ic_dislike_24.xml
  app/src/main/res/drawable/ic_feed_24.xml
  app/src/main/res/drawable/ic_home_24.xml
  app/src/main/res/drawable/ic_like_24.xml
  app/src/main/res/drawable/ic_location_24.xml
  app/src/main/res/drawable/ic_location_searching_24.xml
  app/src/main/res/drawable/ic_my_page_24.xml
  app/src/main/res/drawable/ic_plug_24.xml
  app/src/main/res/drawable/ic_search_24.xml
  app/src/main/res/drawable/ic_settings_24.xml
  app/src/main/res/drawable/ic_wifi_24.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 재성, resource, DONE

#4 Feat/3 bottom navigation
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/MainActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/MainActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BaseActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BaseFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/search/SearchFragment.kt
  app/src/main/res/drawable/selector_bottom_nav_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/menu_bottom.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 재성, feature, DONE

#6 Feat/5 splash screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-hdpi/img_busan.png
  app/src/main/res/drawable-hdpi/img_gangneung.png
  app/src/main/res/drawable-hdpi/img_home_banner.png
  app/src/main/res/drawable-hdpi/img_jeju.png
  app/src/main/res/drawable-hdpi/img_logo.png
  app/src/main/res/drawable-hdpi/img_seoul.png
  app/src/main/res/drawable-hdpi/img_splash_logo.png
  app/src/main/res/drawable-mdpi/img_busan.png
  app/src/main/res/drawable-mdpi/img_gangneung.png
  app/src/main/res/drawable-mdpi/img_home_banner.png
  app/src/main/res/drawable-mdpi/img_jeju.png
  app/src/main/res/drawable-mdpi/img_logo.png
  app/src/main/res/drawable-mdpi/img_seoul.png
  app/src/main/res/drawable-mdpi/img_splash_logo.png
  app/src/main/res/drawable-xhdpi/img_busan.png
  app/src/main/res/drawable-xhdpi/img_gangneung.png
  app/src/main/res/drawable-xhdpi/img_home_banner.png
  app/src/main/res/drawable-xhdpi/img_jeju.png
  app/src/main/res/drawable-xhdpi/img_logo.png
  app/src/main/res/drawable-xhdpi/img_seoul.png
  app/src/main/res/drawable-xhdpi/img_splash_logo.png
  app/src/main/res/drawable-xxhdpi/img_busan.png
  app/src/main/res/drawable-xxhdpi/img_gangneung.png
  app/src/main/res/drawable-xxhdpi/img_home_banner.png
  app/src/main/res/drawable-xxhdpi/img_jeju.png
  app/src/main/res/drawable-xxhdpi/img_logo.png
  app/src/main/res/drawable-xxhdpi/img_seoul.png
  app/src/main/res/drawable-xxhdpi/img_splash_logo.png
  app/src/main/res/drawable-xxxhdpi/img_busan.png
  app/src/main/res/drawable-xxxhdpi/img_gangneung.png
  app/src/main/res/drawable-xxxhdpi/img_home_banner.png
  app/src/main/res/drawable-xxxhdpi/img_jeju.png
  app/src/main/res/drawable-xxxhdpi/img_logo.png
  app/src/main/res/drawable-xxxhdpi/img_seoul.png
  app/src/main/res/drawable-xxxhdpi/img_splash_logo.png
  app/src/main/res/drawable/bg_blue_yellow_gradient.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/colors.xml
Labels: 재성, feature, DONE

#8 Feat/7 auth layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/DialogUtil.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/NavigationUtil.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signin/SignInActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpEmailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpNickNameFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpPasswordFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpVerifyFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/bg_progress.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_sign_up_email.xml
  app/src/main/res/layout/fragment_sign_up_nick_name.xml
  app/src/main/res/layout/fragment_sign_up_password.xml
  app/src/main/res/layout/fragment_sign_up_verify.xml
  app/src/main/res/menu/menu_toolbar.xml
  app/src/main/res/navigation/nav_sign_up.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 재성, layout, DONE

#10 Feat/9 onboarding permission layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/ui/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/onboarding/OnBoardingFirstFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/onboarding/OnBoardingSecondFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/onboarding/OnBoardingThirdFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/permission/CheckPermissionActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpNickNameFragment.kt
  app/src/main/res/drawable/ic_camera_permission.xml
  app/src/main/res/drawable/ic_location_permission.xml
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/ic_storage_permission.xml
  app/src/main/res/drawable/selector_on_boarding_indicator.xml
  app/src/main/res/drawable/shape_on_boarding_selected.xml
  app/src/main/res/drawable/shape_on_boarding_unselected.xml
  app/src/main/res/layout/activity_check_permission.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/fragment_on_boarding_first.xml
  app/src/main/res/layout/fragment_on_boarding_second.xml
  app/src/main/res/layout/fragment_on_boarding_third.xml
  app/src/main/res/navigation/nav_sign_up.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 재성, layout, DONE

#13 [UI] #11 홈 레이아웃 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/category.json
  app/src/main/java/com/comjeong/nomadworker/common/AssetLoader.kt
  app/src/main/java/com/comjeong/nomadworker/common/GlideModule.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/home/HomeAssetLocalDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/home/HomeDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/home/HomeRepository.kt
  app/src/main/java/com/comjeong/nomadworker/model/Category.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BindingAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeCategoryAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeFragment.kt
  app/src/main/res/drawable-hdpi/img_home_banner.png
  app/src/main/res/drawable/bg_black_gradient.xml
  app/src/main/res/drawable/ic_current_location_24.xml
  app/src/main/res/drawable/ic_forward_24.xml
  app/src/main/res/layout/dialog_current_location.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_category.xml
  app/src/main/res/layout/item_home_nearby.xml
  app/src/main/res/layout/item_home_recommend.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: 재성, layout, DONE

#15 Feat/12 mypage layout
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageSettingBottomSheetFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageUserFeedDetailFragment.kt
  app/src/main/res/drawable/bg_solid_red_radius_10.xml
  app/src/main/res/drawable/ic_like_20.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_setting_bottom_sheet.xml
  app/src/main/res/layout/fragment_my_page_user_feed_detail.xml
  app/src/main/res/layout/item_mypage_user_feed.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 승민, layout, DONE

#17 Feat/14 search layout
  app/src/main/java/com/comjeong/nomadworker/ui/search/SearchFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/search/SearchOptionFragment.kt
  app/src/main/res/drawable/bg_bluegrey_radius_10.xml
  app/src/main/res/drawable/bg_white_radius_10_stroke_bluegrey.xml
  app/src/main/res/drawable/selector_chip_background.xml
  app/src/main/res/drawable/selector_chip_stroke.xml
  app/src/main/res/drawable/selector_chip_text_color.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_option.xml
  app/src/main/res/layout/fragment_sign_up_email.xml
  app/src/main/res/layout/fragment_sign_up_nick_name.xml
  app/src/main/res/layout/fragment_sign_up_password.xml
  app/src/main/res/layout/fragment_sign_up_verify.xml
  app/src/main/res/layout/item_search_place.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 재성, layout, DONE

#21 Feat/16 feed layout
  app/src/main/java/com/comjeong/nomadworker/ui/common/DialogUtil.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedContentChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedPhotoChoiceFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/NewFeedPlaceChoiceFragment.kt
  app/src/main/res/drawable/bg_yellow_circle_add_button.xml
  app/src/main/res/drawable/ic_camera_40.xml
  app/src/main/res/drawable/ic_white_add_24.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_new_feed_content_choice.xml
  app/src/main/res/layout/fragment_new_feed_photo_choice.xml
  app/src/main/res/layout/fragment_new_feed_place_choice.xml
  app/src/main/res/layout/item_feed_main.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 승민, layout, DONE

#24 Feat/20 signup
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/NomadWorkerApplication.kt
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/common/Event.kt
  app/src/main/java/com/comjeong/nomadworker/common/EventObserver.kt
  app/src/main/java/com/comjeong/nomadworker/common/RetrofitExt.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/local/NomadSharedPreferences.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/local/home/HomeAssetLocalDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/SignUpRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/HomeDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/SignUpDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/SignUpMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/signup/SignUpRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/signup/SignUpResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/signup/UserEmailResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/signup/UserNicknameResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/NetworkInterceptor.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/SignUpRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/home/HomeRepository.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/NetworkModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/SignUpRepository.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/SignUpResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/UserEmailResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/UserNicknameResult.kt
  app/src/main/java/com/comjeong/nomadworker/model/UserInfo.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/EditTextExt.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpEmailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpNickNameFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpPasswordFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpViewModel.kt
  app/src/main/res/layout/fragment_sign_up_nick_name.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 재성, feature, DONE

#26 Feat/25 login
  app/src/main/java/com/comjeong/nomadworker/data/datasource/local/NomadSharedPreferences.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/signin/SignInRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/signup/SignUpRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/SignInDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/SignInMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/SignUpMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/signin/SignInRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/signin/SignInResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/signin/SignInRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/signup/SignUpRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/signin/SignInResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/signup/SignUpResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/signup/UserEmailResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/signup/UserNicknameResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/signin/SignInRepository.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/signup/SignUpRepository.kt
  app/src/main/java/com/comjeong/nomadworker/model/UserInfo.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signin/SignInActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signin/SignInViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_sign_in.xml
Labels: 재성, feature, DONE

#29 [FEAT] #28 유저 접근 권한 요청 및 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/ui/MainActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/permission/CheckPermissionActivity.kt
  app/src/main/java/com/comjeong/nomadworker/ui/permission/UserPermission.kt
  app/src/main/res/layout/activity_check_permission.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 승민, feature, DONE

#30 [CHORE] #27 Google Maps SDK 연동
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: 재성, feature, IN PROGRESS

#35 Feat/33 user location
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/local/NomadSharedPreferences.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/location/UserLocationRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/UserLocationDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/UserLocationMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/location/UpdateCurrentLocationRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/location/UpdateCurrentLocationResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/location/UserLocationRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/location/UpdateCurrentLocationResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/location/UserLocationRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/UserLocationFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/UserLocationViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_user_location.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  local.properties
Labels: 승민, feature, DONE

#37 Feat/34 local work area
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comjeong/nomadworker/NomadWorkerApplication.kt
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/local/home/HomeAssetLocalDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/home/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/location/UserLocationRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/HomeDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/UserLocationDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/home/HomeRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/HomeMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/UserLocationMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/home/LocationCategoryResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/home/LocationPlaceResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/home/UpdateCurrentLocationRequestData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/home/UpdateCurrentLocationResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/PlaceApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/home/HomeRepository.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/home/HomeRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/location/UserLocationRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/NetworkModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/home/LocationCategoryResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/home/LocationPlaceResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/home/UpdateCurrentLocationResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/home/HomeRepository.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/location/UserLocationRepository.kt
  app/src/main/java/com/comjeong/nomadworker/model/Category.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BindingAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeCategoryAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/UserLocationFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceRegionFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/splash/SplashActivity.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_category.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/dimens.xml
  local.properties
Labels: 재성, feature, DONE

#39 [FEAT] #38 지역별 근무 장소 상세 API 구현
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/home/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/place/PlaceRegionRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/home/HomeRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/place/PlaceRegionRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/HomeMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/PlaceMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/place/LocationPlaceResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/PlaceApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/home/HomeRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/place/PlaceRegionRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/home/LocationCategoryResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/home/HomeRepository.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/place/PlaceRegionRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeCategoryAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceRegionAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceRegionFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceRegionViewModel.kt
  app/src/main/res/layout/fragment_place_region.xml
  app/src/main/res/layout/item_search_place.xml
Labels: 재성, feature, DONE

#41 Feat/40 place detail
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/place/PlaceDetailRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/place/PlaceDetailRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/PlaceMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/place/PlaceDetailResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/PlaceApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/place/PlaceDetailRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/place/PlaceRegionRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/place/LocationPlaceResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/place/PlaceDetailResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/home/HomeRepository.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/place/PlaceDetailRepository.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/place/PlaceRegionRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BindingAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceDetailViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceRegionAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceRegionFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/place/PlaceRegionViewModel.kt
  app/src/main/res/layout/fragment_place_detail.xml
  app/src/main/res/layout/item_search_place.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
  app/src/main/res/values/strings.xml
Labels: 재성, feature, DONE

#43 Feat/42 nearby place
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/home/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/place/PlaceDetailRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/place/PlaceRegionRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/home/HomeRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/place/PlaceDetailDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/place/PlaceRegionDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/HomeMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/place/NearbyPlaceResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/PlaceApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/home/HomeRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/place/PlaceDetailRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/place/PlaceRegionRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/place/NearbyPlaceResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/home/HomeRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/NearbyPlaceAdapter.kt
  app/src/main/res/layout/item_home_nearby.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
Labels: 재성, feature, DONE

#45 Feat/44 like place
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/home/HomeRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/home/HomeRemoteDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/HomeMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/home/RecommendPlaceResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/PlaceApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/home/HomeRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/home/RecommendPlaceResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/home/HomeRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/HomeViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/home/RecommendPlaceAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_recommend.xml
Labels: 재성, feature, DONE

#47 [FEAT] #46 피드 전체 API 구현
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/feed/FeedsRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/feed/FeedsDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/FeedMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/feed/TotalFeedsResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/FeedApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/feed/FeedRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/NetworkModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/feed/TotalFeedsResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/feed/FeedRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/common/BindingAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedAdapter.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedViewModel.kt
  app/src/main/res/layout/item_feed_main.xml
Labels: 재성, feature, DONE

#49 Feat/48 mypage
  app/src/main/java/com/comjeong/nomadworker/common/Constants.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/remote/mypage/MyPageRemoteDataSourceImpl.kt
  app/src/main/java/com/comjeong/nomadworker/data/datasource/source/mypage/MyPageDataSource.kt
  app/src/main/java/com/comjeong/nomadworker/data/mapper/MyPageMapper.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/mypage/UserFeedDetailResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/mypage/UserInfoResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/model/mypage/UserTotalFeedsResponseData.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/AuthApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/network/api/FeedApi.kt
  app/src/main/java/com/comjeong/nomadworker/data/repository/mypage/MyPageRepositoryImpl.kt
  app/src/main/java/com/comjeong/nomadworker/di/DataSourceModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/RepositoryModule.kt
  app/src/main/java/com/comjeong/nomadworker/di/ViewModelModule.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/feed/UserTotalFeedResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/mypage/UserFeedDetailResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/model/mypage/UserInfoResult.kt
  app/src/main/java/com/comjeong/nomadworker/domain/repository/mypage/MyPageRepository.kt
  app/src/main/java/com/comjeong/nomadworker/ui/feed/FeedViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageUserFeedDetailFragment.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/comjeong/nomadworker/ui/mypage/UserFeedAdapter.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_page_user_feed_detail.xml
  app/src/main/res/layout/item_mypage_user_feed.xml
  app/src/main/res/navigation/nav_bottom_graph.xml
Labels: 재성, feature, DONE
